name: Pack Icons into JSON

on: 
  push:
  schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  packaging:
    runs-on: ubuntu-latest

    steps:
      - name: checkout this repo
        uses: actions/checkout@v4
      - name: checkout material icons repo
        # We only need the SVG data.
        # The rest of the repo history is too big for ubuntu-latest runner.
        # We also need enought history to `git describe` the version since last tag.
        # Do a sparse-checkout that only gets SVG data and history on master branch.
        run: |-
          git clone --filter=blob:none --no-checkout https://github.com/google/material-design-icons md-icons
          cd md-icons
          git sparse-checkout set -cone
          git checkout master
          git sparse-checkout set src
      - name: checkout sphinx-design repo
        uses: actions/checkout@v4
        with:
          repository: executablebooks/sphinx-design
          path: sphinx-design
      - name: describe icons version & and commit sha
        working-directory: md-icons
        id: md-icon-version
        run: |
          echo "tag=$(git describe --tags --abbrev=6)" >> $GITHUB_OUTPUT
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x' 
      - name: compile the json files
        id: compiled
        run: python walk_svg_to_json.py --path=md-icons
      - name: create version file
        run: |
          echo "using github.com/google/material-design-icons" >> compiled/material-icons_VERSION.txt
          echo "v${{ steps.md-icon-version.outputs.tag }}" >> compiled/material-icons_VERSION.txt
          echo "${{ steps.md-icon-version.outputs.sha }}" >> compiled/material-icons_VERSION.txt
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-v${{ steps.md-icon-version.outputs.tag }}
          path: compiled/
